require 'rails_helper'

# Test OperatorAPI used by merchant api subdomain
#
describe OperatorAPI, type: :request do
  include OperatorRequests

  before do
    host! "#{Settings.merchant_api_subdomain}.example.com"
    vendor.reload # reload uuid which is generated by sql
  end

  #  include Rack::Test::Methods
  it 'ping' do
    get '/v1/ping', headers: { 'Merchant-ID' => vendor.uuid }
    expect(response.status).to eq 200
  end

  it 'whoami' do
    get '/v1/whoami', headers: { 'Merchant-ID' => vendor.uuid }

    expect(response.status).to eq 200
  end
end
