module RussianPost
  extend AutoLogger

  SIMPLE_CATEGORY = 'SIMPLE'.freeze
  ORDERED_CATEGORY = 'ORDERED'.freeze
  ORDINARY_CATEGORY = 'ORDINARY'.freeze
  WITH_DECLARED_VALUE_CATEGORY = 'WITH_DECLARED_VALUE'.freeze
  WITH_DECLARED_VALUE_AND_CASH_ON_DELIVERY_CATEGORY = 'WITH_DECLARED_VALUE_AND_CASH_ON_DELIVERY'.freeze
  WITH_DECLARED_VALUE_AND_COMPULSORY_PAYMENT_CATEGORY = 'WITH_DECLARED_VALUE_AND_COMPULSORY_PAYMENT'.freeze
  WITH_COMPULSORY_PAYMENT_CATEGORY = 'WITH_COMPULSORY_PAYMENT'.freeze

  MAIL_CATEGORIES = [
    SIMPLE_CATEGORY,
    ORDERED_CATEGORY,
    ORDINARY_CATEGORY,
    WITH_DECLARED_VALUE_CATEGORY,
    WITH_DECLARED_VALUE_AND_CASH_ON_DELIVERY_CATEGORY,
    WITH_DECLARED_VALUE_AND_COMPULSORY_PAYMENT_CATEGORY,
    WITH_COMPULSORY_PAYMENT_CATEGORY
  ].freeze

  PAYMENT_REQUIRE = [WITH_DECLARED_VALUE_AND_CASH_ON_DELIVERY_CATEGORY].freeze
  INSURANCE_VALUE_REQUIRE = [WITH_DECLARED_VALUE_CATEGORY, WITH_DECLARED_VALUE_AND_CASH_ON_DELIVERY_CATEGORY].freeze

  POSTAL_PARCEL_TYPE = 'POSTAL_PARCEL'.freeze
  ONLINE_PARCEL_TYPE = 'ONLINE_PARCEL'.freeze
  ONLINE_COURIER_TYPE = 'ONLINE_COURIER'.freeze
  EMS_TYPE = 'EMS'.freeze
  EMS_OPTIMAL_TYPE = 'EMS_OPTIMAL'.freeze
  EMS_RT_TYPE = 'EMS_RT'.freeze
  EMS_TENDER_TYPE = 'EMS_TENDER'.freeze
  LETTER_TYPE = 'LETTER'.freeze
  LETTER_CLASS_1_TYPE = 'LETTER_CLASS_1'.freeze
  BANDEROL_TYPE = 'BANDEROL'.freeze
  BUSINESS_COURIER_TYPE = 'BUSINESS_COURIER'.freeze
  BUSINESS_COURIER_ES_TYPE = 'BUSINESS_COURIER_ES'.freeze
  PARCEL_CLASS_1_TYPE = 'PARCEL_CLASS_1'.freeze
  BANDEROL_CLASS_1_TYPE = 'BANDEROL_CLASS_1'.freeze
  VGPO_CLASS_1_TYPE =  'VGPO_CLASS_1'.freeze
  SMALL_PACKET_TYPE =  'SMALL_PACKET'.freeze
  EASY_RETURN_TYPE = 'EASY_RETURN'.freeze
  VSD_TYPE = 'VSD'.freeze
  ECOM_TYPE = 'ECOM'.freeze
  COMBINED_TYPE = 'COMBINED'.freeze

  MAIL_TYPES = [
    POSTAL_PARCEL_TYPE,
    ONLINE_PARCEL_TYPE,
    ONLINE_COURIER_TYPE,
    EMS_TYPE,
    EMS_OPTIMAL_TYPE,
    EMS_RT_TYPE,
    EMS_TENDER_TYPE,
    LETTER_TYPE,
    LETTER_CLASS_1_TYPE,
    BANDEROL_TYPE,
    BUSINESS_COURIER_TYPE,
    BUSINESS_COURIER_ES_TYPE,
    PARCEL_CLASS_1_TYPE,
    VGPO_CLASS_1_TYPE,
    SMALL_PACKET_TYPE,
    EASY_RETURN_TYPE,
    VSD_TYPE,
    ECOM_TYPE,
    COMBINED_TYPE,
  ].freeze
end
